"""AnalysisReport entity for DS deep analysis results.

Stores comprehensive analysis reports including metadata about depth,
strategy, linked insights, artifacts, and communication logs.

Feature 33: DS Deep Analysis.
"""

from __future__ import annotations

import enum
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import JSON, DateTime, Enum, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from src.storage.models import Base


class ReportStatus(str, enum.Enum):
    """Status of an analysis report."""

    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class AnalysisReport(Base):
    """A comprehensive analysis report from the DS team.

    Links to insights, artifacts (charts/CSVs), and captures the
    communication log between specialists.

    Feature 33: DS Deep Analysis.
    """

    __tablename__ = "analysis_reports"

    id: Mapped[str] = mapped_column(String(36), primary_key=True)

    # Report metadata
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    analysis_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
        doc="AnalysisType value",
    )
    depth: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        doc="AnalysisDepth value: quick, standard, deep",
    )
    strategy: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        doc="ExecutionStrategy value: parallel, teamwork",
    )

    # Status
    status: Mapped[ReportStatus] = mapped_column(
        Enum(ReportStatus),
        nullable=False,
        default=ReportStatus.RUNNING,
        index=True,
    )

    # Content
    summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        doc="Executive summary of the analysis",
    )

    # Linked data (JSON arrays)
    insight_ids: Mapped[list[str]] = mapped_column(
        JSON,
        nullable=False,
        default=list,
        doc="IDs of insights generated by this report",
    )
    artifact_paths: Mapped[list[str]] = mapped_column(
        JSON,
        nullable=False,
        default=list,
        doc="Filenames of artifacts (charts, CSVs) produced",
    )
    communication_log: Mapped[list[dict[str, Any]]] = mapped_column(
        JSON,
        nullable=False,
        default=list,
        doc="Chronological log of inter-agent communications",
    )

    # Counts for quick reference
    communication_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        doc="Number of inter-agent communication entries",
    )

    # Traceability
    conversation_id: Mapped[str | None] = mapped_column(
        String(36),
        nullable=True,
        index=True,
        doc="Originating conversation ID",
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    def __repr__(self) -> str:
        return f"<AnalysisReport {self.id[:8]} status={self.status.value} depth={self.depth}>"

    def mark_completed(self, summary: str | None = None) -> None:
        """Mark report as completed."""
        self.status = ReportStatus.COMPLETED
        self.completed_at = datetime.now(UTC)
        if summary:
            self.summary = summary

    def mark_failed(self, summary: str | None = None) -> None:
        """Mark report as failed."""
        self.status = ReportStatus.FAILED
        self.completed_at = datetime.now(UTC)
        if summary:
            self.summary = summary
